# Generated by Django 4.1.7 on 2023-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_eid_alter_employee_epaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=50),
        ),
    ]
